### ISSUE TITLE
UnboundLocalError: local variable 'network_definition' referenced before assignment

### ISSUE THREAD

**Issue by Ki6an** [ELS-RD/transformer-deploy#100]
when running the https://github.com/ELS-RD/transformer-deploy/blob/main/demo/generative-model/t5_tensorrt.py file in a container created from the source repo, 
getting the following error: 

```bash
/usr/src/tensorrt/bin/trtexec --onnx=test-dec-if.onnx --useSpinWait --verbose --dumpLayerInfo --profilingVerbosity=detailed  --minShapes=input_ids:4x1,encoder_hidden_states:4x1x512,final_seq_len:1,past_key_values.0.decoder.key:4x8x0x64,past_key_values.0.decoder.value:4x8x0x64,past_key_values.0.encoder.key:4x8x0x64,past_key_values.0.encoder.value:4x8x0x64,past_key_values.1.decoder.key:4x8x0x64,past_key_values.1.decoder.value:4x8x0x64,past_key_values.1.encoder.key:4x8x0x64,past_key_values.1.encoder.value:4x8x0x64,past_key_values.2.decoder.key:4x8x0x64,past_key_values.2.decoder.value:4x8x0x64,past_key_values.2.encoder.key:4x8x0x64,past_key_values.2.encoder.value:4x8x0x64,past_key_values.3.decoder.key:4x8x0x64,past_key_values.3.decoder.value:4x8x0x64,past_key_values.3.encoder.key:4x8x0x64,past_key_values.3.encoder.value:4x8x0x64,past_key_values.4.decoder.key:4x8x0x64,past_key_values.4.decoder.value:4x8x0x64,past_key_values.4.encoder.key:4x8x0x64,past_key_values.4.encoder.value:4x8x0x64,past_key_values.5.decoder.key:4x8x0x64,past_key_values.5.decoder.value:4x8x0x64,past_key_values.5.encoder.key:4x8x0x64,past_key_values.5.encoder.value:4x8x0x64  --optShapes=input_ids:4x1,encoder_hidden_states:4x10x512,final_seq_len:1,past_key_values.0.decoder.key:4x8x100x64,past_key_values.0.decoder.value:4x8x100x64,past_key_values.0.encoder.key:4x8x10x64,past_key_values.0.encoder.value:4x8x10x64,past_key_values.1.decoder.key:4x8x100x64,past_key_values.1.decoder.value:4x8x100x64,past_key_values.1.encoder.key:4x8x10x64,past_key_values.1.encoder.value:4x8x10x64,past_key_values.2.decoder.key:4x8x100x64,past_key_values.2.decoder.value:4x8x100x64,past_key_values.2.encoder.key:4x8x10x64,past_key_values.2.encoder.value:4x8x10x64,past_key_values.3.decoder.key:4x8x100x64,past_key_values.3.decoder.value:4x8x100x64,past_key_values.3.encoder.key:4x8x10x64,past_key_values.3.encoder.value:4x8x10x64,past_key_values.4.decoder.key:4x8x100x64,past_key_values.4.decoder.value:4x8x100x64,past_key_values.4.encoder.key:4x8x10x64,past_key_values.4.encoder.value:4x8x10x64,past_key_values.5.decoder.key:4x8x100x64,past_key_values.5.decoder.value:4x8x100x64,past_key_values.5.encoder.key:4x8x10x64,past_key_values.5.encoder.value:4x8x10x64  --maxShapes=input_ids:4x200,encoder_hidden_states:4x200x512,final_seq_len:1,past_key_values.0.decoder.key:4x8x200x64,past_key_values.0.decoder.value:4x8x200x64,past_key_values.0.encoder.key:4x8x200x64,past_key_values.0.encoder.value:4x8x200x64,past_key_values.1.decoder.key:4x8x200x64,past_key_values.1.decoder.value:4x8x200x64,past_key_values.1.encoder.key:4x8x200x64,past_key_values.1.encoder.value:4x8x200x64,past_key_values.2.decoder.key:4x8x200x64,past_key_values.2.decoder.value:4x8x200x64,past_key_values.2.encoder.key:4x8x200x64,past_key_values.2.encoder.value:4x8x200x64,past_key_values.3.decoder.key:4x8x200x64,past_key_values.3.decoder.value:4x8x200x64,past_key_values.3.encoder.key:4x8x200x64,past_key_values.3.encoder.value:4x8x200x64,past_key_values.4.decoder.key:4x8x200x64,past_key_values.4.decoder.value:4x8x200x64,past_key_values.4.encoder.key:4x8x200x64,past_key_values.4.encoder.value:4x8x200x64,past_key_values.5.decoder.key:4x8x200x64,past_key_values.5.decoder.value:4x8x200x64,past_key_values.5.encoder.key:4x8x200x64,past_key_values.5.encoder.value:4x8x200x64--saveEngine='trt-t5-dec.plan' |& > logs.txt
Traceback (most recent call last):
  File "t5_tensorrt.py", line 421, in <module>
    engine: ICudaEngine = build_engine(
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/backends/trt_utils.py", line 213, in build_engine
    trt_engine = builder.build_serialized_network(network_definition, config)
UnboundLocalError: local variable 'network_definition' referenced before assignment
```

**Comment by pommedeterresautee** [comment]
Thanks @Ki6an !
Indeed it's a bug recently introduced, source code should be (note there is no more `network_definition` variable):

```python
def build_engine(
    runtime: Runtime,
    onnx_file_path: str,
    logger: Logger,
    workspace_size: int,
    fp16: bool,
    int8: bool,
    fp16_fix: Callable[[INetworkDefinition], INetworkDefinition] = fix_fp16_network,
    profiling: bool = False,
    **kwargs,
) -> ICudaEngine:
    """
    Convert ONNX file to TensorRT engine.
    It supports dynamic shape, however it's advised to keep sequence length fix as it hurts performance otherwise.
    Dynamic batch size doesn't hurt performance and is highly advised.
    Batch size can provided through different ways:

    * **min_shape**, **optimal_shape**, **max_shape**: for simple case, 3 tuples of int when all
    input tensors have the same shape
    * **input_shapes**: a list of TensorRTShape with names if there are several input tensors with different shapes

    **TIP**: minimum batch size should be 1 in most cases.

    :param runtime: global variable shared accross inference call / model building
    :param onnx_file_path: path to the ONNX file
    :param logger: specific logger to TensorRT
    :param workspace_size: GPU memory to use during the building, more is always better.
        If there is not enough memory, some optimization may fail, and the whole conversion process will crash.
    :param fp16: enable FP16 precision, it usually provide a 20-30% boost compared to ONNX Runtime.
    :param int8: enable INT-8 quantization, best performance but model should have been quantized.
    :param fp16_fix: a function to set FP32 precision on some nodes to fix FP16 overflow
    :param profiling: enable profiling support of the model.
        https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Profiler.html
    :return: TensorRT engine to use during inference
    """
    # default input shape
    if "min_shape" in kwargs and "optimal_shape" in kwargs and "max_shape" in kwargs:
        default_shape = TensorRTShape(
            min_shape=kwargs["min_shape"],
            optimal_shape=kwargs["optimal_shape"],
            max_shape=kwargs["max_shape"],
            input_name=None,
        )
        input_shapes = [default_shape]
    else:
        assert "input_shapes" in kwargs, "missing input shapes"
        input_shapes: List[TensorRTShape] = kwargs["input_shapes"]

    with trt.Builder(logger) as builder:  # type: Builder
        with builder.create_network(
            flags=1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
        ) as network_def:  # type: INetworkDefinition
            with trt.OnnxParser(network_def, logger) as parser:  # type: OnnxParser
                # The maximum batch size which can be used at execution time,
                # and also the batch size for which the ICudaEngine will be optimized.
                builder.max_batch_size = max([s.max_shape[0] for s in input_shapes])
                config: IBuilderConfig = builder.create_builder_config()
                config.max_workspace_size = workspace_size
                config.set_tactic_sources(
                    tactic_sources=1 << int(trt.TacticSource.CUBLAS)
                    | 1 << int(trt.TacticSource.CUBLAS_LT)
                    | 1 << int(trt.TacticSource.CUDNN)  # trt advised to use cuDNN for transfo architecture
                )
                if profiling:
                    config.profiling_verbosity = trt.ProfilingVerbosity.DETAILED
                if int8:
                    config.set_flag(trt.BuilderFlag.INT8)
                if fp16:
                    config.set_flag(trt.BuilderFlag.FP16)
                config.set_flag(trt.BuilderFlag.DISABLE_TIMING_CACHE)
                # https://github.com/NVIDIA/TensorRT/issues/1196 (sometimes big diff in output when using FP16)
                config.set_flag(trt.BuilderFlag.OBEY_PRECISION_CONSTRAINTS)
                logger.log(msg="parsing TensorRT model", severity=trt.ILogger.INFO)
                with open(onnx_file_path, "rb") as f:
                    # file path needed for models with external dataformat
                    # https://github.com/onnx/onnx-tensorrt/issues/818
                    parser.parse(model=f.read(), path=onnx_file_path)
                profile: IOptimizationProfile = builder.create_optimization_profile()
                # duplicate default shape (one for each input)
                if len(input_shapes) == 1 and input_shapes[0].input_name is None:
                    names = [network_def.get_input(num_input).name for num_input in range(network_def.num_inputs)]
                    input_shapes = input_shapes[0].generate_multiple_shapes(input_names=names)

                for shape in input_shapes:
                    shape.check_validity()
                    profile.set_shape(
                        input=shape.input_name,
                        min=shape.min_shape,
                        opt=shape.optimal_shape,
                        max=shape.max_shape,
                    )
                if "shape_tensors" in kwargs:
                    for shape in kwargs["shape_tensors"]:
                        profile.set_shape_input(
                            input=shape.input_name,
                            min=shape.min_shape,
                            opt=shape.optimal_shape,
                            max=shape.max_shape,
                        )
                config.add_optimization_profile(profile)
                if fp16:
                    network_def = fp16_fix(network_def)

                logger.log(
                    msg="building engine. depending on model size this may take a while", severity=trt.ILogger.WARNING
                )
                start = time()
                trt_engine = builder.build_serialized_network(network_def, config)
                engine: ICudaEngine = runtime.deserialize_cuda_engine(trt_engine)
                logger.log(msg=f"building engine took {time() - start:4.1f} seconds", severity=trt.ILogger.WARNING)
                assert engine is not None, "error during engine generation, check error messages above :-("
                return engine
```

Just tried with the fix and works like a charm.

I will push a fix.

**Comment by Ki6an** [comment]
thank you for the response and the fix... 

I ran the  https://github.com/ELS-RD/transformer-deploy/blob/main/demo/generative-model/t5_tensorrt.py file, it converts the decoder successfully to tensorrt. however, I noticed that it outputs only 4 tensors. Should not it output all `past_key_values` and one `logit`?

```
torch.Size([1, 32128])
torch.Size([1, 32128])
torch.Size([1, 32128])
torch.Size([1, 32128])
```
