### ISSUE TITLE
Failed to load private model

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [ELS-RD/transformer-deploy#132]
Hi,

I tried to convert a private model of sentence-transformer on the Hugging Face Hub:
```
docker run -it --rm --gpus all \
    -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 \
    bash -c "cd /project && \
    convert_model -m \"Matthieu/paraphrase-multilingual-MiniLM-L12-v2-pooling-GPLv2\" \
    --backend tensorrt onnx \
    --task embedding \
    --seq-len 16 128 128 \
    --auth-token XXX"
```
However, the download of config.json file failed with the following message:
```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.01 (build 31237563)

Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 451/451 [00:00<00:00, 650kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.83M/4.83M [00:02<00:00, 2.48MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16.3M/16.3M [00:07<00:00, 2.41MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 280/280 [00:00<00:00, 425kB/s]
401 Client Error: Unauthorized for url: https://huggingface.co/Matthieu/paraphrase-multilingual-MiniLM-L12-v2-pooling-GPLv2/resolve/main/config.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 585, in _get_config_dict
    resolved_config_file = cached_path(
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1846, in cached_path
    output_path = get_from_cache(
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 2050, in get_from_cache
    _raise_for_status(r)
  File "/usr/local/lib/python3.8/dist-packages/transformers/file_utils.py", line 1977, in _raise_for_status
    request.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/Matthieu/paraphrase-multilingual-MiniLM-L12-v2-pooling-GPLv2/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/convert_model", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 357, in entrypoint
    main(commands=args)
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 152, in main
    model_config: PretrainedConfig = AutoConfig.from_pretrained(pretrained_model_name_or_path=commands.model)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/configuration_auto.py", line 612, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 537, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 618, in _get_config_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co/' to load this model and it looks like Matthieu/paraphrase-multilingual-MiniLM-L12-v2-pooling-GPLv2 is not the path to a directory conaining a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```

Any advice?

Thanks!

**Comment by ayoub-louati** [comment]
Hi @Matthieu-Tinycoaching, it is either related to authentication token (which is not valid) or to the model name. can you please try with this command with the good auth-token:
```
docker run -it --rm --gpus all \
    -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 \
    bash -c "cd /project && \
    convert_model -m Matthieu/paraphrase-multilingual-MiniLM-L12-v2-pooling-GPLv2 \
    --backend tensorrt onnx \
    --task embedding \
    --seq-len 16 128 128 \
    --auth-token XXX"
```

**Comment by Matthieu-Tinycoaching** [comment]
Hi @ayoub-louati thanks for your feedback.

I tested your proposition but it gave the same result. But the auth-token is good and so is the model name since it managed to download the first 4 items then failed on `config.json`...

**Comment by ayoub-louati** [comment]
@pommedeterresautee I think we are missing the authentication token when loading the configuration, i'll do a quick fix.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @pommedeterresautee when will be available the fix in the new docker image?

**Comment by ayoub-louati** [comment]
@Matthieu-Tinycoaching We are releasing the 0.5.1 version which contains the fix for private models today.
