### ISSUE TITLE
TRT error on fresh install

### ISSUE THREAD

**Issue by sam-writer** [ELS-RD/transformer-deploy#21]
Running the example command on a fresh install, I get:

```
$ convert_model -m roberta-large-mnli --backend tensorrt onnx pytorch --seq-len 16 128 128 --batch-size 1 32 32

...
    engine = build_engine(
  File "/home/sam_havens/transformer-deploy/venv/lib/python3.8/site-packages/transformer_deploy/backends/trt_utils.py", line 181, in build_engine
    engine: ICudaEngine = runtime.deserialize_cuda_engine(trt_engine)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7f5df2f18bb0>, None
```

<details>
<summary>Full error</summary>

```
$ convert_model -m roberta-large-mnli --backend tensorrt onnx pytorch --seq-len 16 128 128 --batch-size 1 32 32

Some weights of the model checkpoint at roberta-large-mnli were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:604] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:81] The total number of bytes read was 1421594533
[12/08/2021-00:18:52] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[12/08/2021-00:19:08] [TRT] [W] Output type must be INT32 for shape outputs
[12/08/2021-00:19:08] [TRT] [W] Output type must be INT32 for shape outputs
[12/08/2021-00:19:08] [TRT] [W] Output type must be INT32 for shape outputs
[12/08/2021-00:19:12] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are:
[12/08/2021-00:19:12] [TRT] [W]  (# 1 (SHAPE input_ids))
[12/08/2021-00:19:12] [TRT] [W]  (# 0 (SHAPE attention_mask))
Warning: Slice op (Unnamed Layer_ 90) [Slice]_slice cannot slice along a uniform dimension.
[12/08/2021-00:19:39] [TRT] [W] Skipping tactic 0 due to Myelin error: No results returned from cublas heuristic search
[12/08/2021-00:19:39] [TRT] [W] Myelin graph with multiple dynamic values may have poor performance if they differ. Dynamic values are:
[12/08/2021-00:19:39] [TRT] [W]  (# 1 (SHAPE input_ids))
[12/08/2021-00:19:39] [TRT] [W]  (# 0 (SHAPE attention_mask))
Warning: Slice op (Unnamed Layer_ 90) [Slice]_slice cannot slice along a uniform dimension.
[12/08/2021-00:20:10] [TRT] [W] Skipping tactic 0 due to Myelin error: No results returned from cublas heuristic search
[12/08/2021-00:20:10] [TRT] [E] 10: [optimizer.cpp::computeCosts::2011] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[roberta.embeddings.token_type_embeddings.weight...(Unnamed Layer* 3884) [Shuffle]]}.)
[12/08/2021-00:20:10] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )
Traceback (most recent call last):
  File "/home/sam_havens/transformer-deploy/venv/bin/convert_model", line 11, in <module>
    load_entry_point('transformer-deploy==0.1.1', 'console_scripts', 'convert_model')()
  File "/home/sam_havens/transformer-deploy/venv/lib/python3.8/site-packages/transformer_deploy/convert.py", line 129, in main
    engine = build_engine(
  File "/home/sam_havens/transformer-deploy/venv/lib/python3.8/site-packages/transformer_deploy/backends/trt_utils.py", line 181, in build_engine
    engine: ICudaEngine = runtime.deserialize_cuda_engine(trt_engine)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7f5df2f18bb0>, None
```

</details>

If you have any ideas, I'd appreciate it! Thank you.

EDIT:

<details>
<summary>nvidia-smi</summary>

```
$ nvidia-smi
Wed Dec  8 00:35:05 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8    10W /  70W |    105MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1030      G   /usr/lib/xorg/Xorg                 95MiB |
|    0   N/A  N/A      1213      G   /usr/bin/gnome-shell                8MiB |
+-----------------------------------------------------------------------------+
```

</details>

<details>
<summary>pip freeze output</summary>

```
$ pip freeze
anyio==3.4.0
appdirs==1.4.4
asgiref==3.4.1
attrs==21.2.0
black==21.12b0
Brotli==1.0.9
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.9
click==8.0.3
colored==1.4.3
coloredlogs==15.0.1
cryptography==36.0.0
cycler==0.11.0
distro==1.6.0
docker==5.0.3
fastapi==0.70.0
filelock==3.4.0
flake8==4.0.1
flatbuffers==2.0
fonttools==4.28.3
gevent==21.8.0
geventhttpclient==1.5.3
greenlet==1.1.2
grpcio==1.42.0
gunicorn==20.1.0
h11==0.12.0
httplib2==0.20.2
huggingface-hub==0.2.1
humanfriendly==10.0
idna==3.3
iniconfig==1.1.1
isort==5.10.1
joblib==1.1.0
kiwisolver==1.3.2
llvmlite==0.37.0
Mako==1.1.6
MarkupSafe==2.0.1
matplotlib==3.5.0
mccabe==0.6.1
mpmath==1.2.1
mypy-extensions==0.4.3
numba==0.54.1
numpy==1.21.4
nvidia-cublas-cu11==2021.10.25
nvidia-cublas-cu115==11.7.3.1
nvidia-cuda-runtime-cu11==2021.10.25
nvidia-cuda-runtime-cu115==11.5.50
nvidia-cudnn-cu11==2021.11.18
nvidia-cudnn-cu115==8.3.0.98
nvidia-pyindex==1.0.9
nvidia-tensorrt==8.2.1.8
onnx==1.10.2
onnx-graphsurgeon==0.3.14
onnxruntime-gpu==1.10.0
packaging==21.3
pathspec==0.9.0
pdfkit==1.0.0
Pillow==8.4.0
platformdirs==2.4.0
pluggy==1.0.0
polygraphy==0.33.2
prometheus-client==0.12.0
protobuf==3.19.1
psutil==5.8.0
py==1.11.0
pycodestyle==2.8.0
pycparser==2.21
pycuda==2021.1
pydantic==1.8.2
pyflakes==2.4.0
pyparsing==3.0.6
pytest==6.2.5
python-dateutil==2.8.2
python-rapidjson==1.5
pytools==2021.2.9
PyYAML==6.0
regex==2021.11.10
requests==2.26.0
sacremoses==0.0.46
sentencepiece==0.1.96
setuptools-scm==6.3.2
six==1.16.0
sniffio==1.2.0
starlette==0.16.0
sympy==1.9
tokenizers==0.10.3
toml==0.10.2
tomli==1.2.2
torch==1.10.0+cu113
tqdm==4.62.3
transformer-deploy==0.1.1
transformers==4.12.5
triton-model-analyzer==1.10.0
tritonclient==2.16.0
typing-extensions==4.0.1
urllib3==1.26.7
uvicorn==0.15.0
websocket-client==1.2.3
zope.event==4.5.0
zope.interface==5.4.0
```

</details>

**Comment by pommedeterresautee** [comment]
Do you know if you have TensorRT 8.2 installed on your machine? (released a few week ago)
I am waiting the Nvidia docker images with updated TensorRT to update the doc and avoid those kind of reproducibility issue...
Moreover, can you try the `quantization` branch?

**Comment by sam-writer** [comment]
Thank you @pommedeterresautee ! I had to upgrade CUDA
