### ISSUE TITLE
Calibration failure occurred with no scaling factors detected

### ISSUE THREAD

**Issue by v1nc3nt27** [ELS-RD/transformer-deploy#43]
Hey, 

first of all, thanks a lot for your great work. This repo was already a great help to me.

With your quantization update for INT8, however, I ran into a problem. As soon as I activate `--quantization`, I get the following error:

```
[01/14/2022-11:18:37] [TRT] [W] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32 or Bool.
[01/14/2022-11:18:37] [TRT] [E] 4: [standardEngineBuilder.cpp::initCalibrationParams::1402] Error Code 4: Internal Error (Calibration failure occurred with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
[01/14/2022-11:18:37] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::609] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed. )

Traceback (most recent call last):
  File "/data/repos/transformer-deploy/src/transformer_deploy/convert.py", line 326, in <module>
    entrypoint()
  File "/data/repos/transformer-deploy/src/transformer_deploy/convert.py", line 322, in entrypoint
    main(commands=args)
  File "/data/repos/transformer-deploy/src/transformer_deploy/convert.py", line 216, in main
    engine: ICudaEngine = build_engine(
  File "/data/repos/transformer-deploy/src/transformer_deploy/backends/trt_utils.py", line 181, in build_engine
    engine: ICudaEngine = runtime.deserialize_cuda_engine(trt_engine)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7feb14128e30>, None
```
The problem in the traceback is then just that the `trt_engine` will be `None`. I don't get any other warnings or errors, so I'm a bit at a loss. I've tried with distilroberta-base and also with bert-base-uncased, but I get the same error each time. Did you, by any chance, run into the same problem at some point in time or do you see what the issue may be?

Thanks a lot in advance!

**Comment by DeDeckerThomas** [comment]
Hey :)

I have the same problem. The INT-8 quantization does work in the end-to-end notebook in the demo directory, but not with the command in the docker container. 

Also, when I deploy it on NVIDIA Triton, it also seems to be slower than in the notebook. (I am using a destilbert model)

I have no idea what the issue could be, but I hope there is a solution.

**Comment by pommedeterresautee** [comment]
@v1nc3nt27 it seems the model has not been calibrated. It's a process to run before launching the conversion.
You can check here for more info on what it is and how to do it (it's easy): https://els-rd.github.io/transformer-deploy/quantization_intro/

@DeDeckerThomas regarding Triton, it's strange, we have not seen such behavior. Which version of TensorRT are you using for the compilation part?
What kind of perf difference did you noticed?

**Comment by DeDeckerThomas** [comment]
I am using TensorRT 8.2.2.1. 
First I used the end-to-end quantization notebook with a destilbert model and I got faster inference for a batch of 32 with TensorRT. (I compared this with ONNX (FP16))

TensorRT (INT8):
[TensorRT (INT-8)] mean=10.92ms, sd=0.33ms, min=10.69ms, max=12.60ms, median=10.82ms, 95p=11.69ms, 99p=12.49ms

ONNX (FP16):
[ONNX Runtime GPU (FP16)] mean=18.85ms, sd=1.79ms, min=16.02ms, max=24.26ms, median=18.28ms, 95p=22.13ms, 99p=22.87ms

So then I decided to deploy it to triton and test it with a token length of 128 and batch size 1. (I used the tritonclient.py in the demo directory)
TensorRT (INT8):
[triton transformers] mean=7.94ms, sd=1.80ms, min=6.32ms, max=54.31ms, median=7.59ms, 95p=9.90ms, 99p=11.56ms 

ONNX (FP16):
[triton transformers] mean=7.76ms, sd=1.43ms, min=6.01ms, max=36.68ms, median=7.40ms, 95p=10.11ms, 99p=11.28ms

To my surprising ONNX (FP16) seems to be faster. Or is this because I am only testing with a batch size of 1? In other words, is it faster than ONNX with bigger batch sizes a normal behaviour?

**Comment by pommedeterresautee** [comment]
One thing to keep in mind is that when you build your TensorRT engine it will optimize it for some parameters (called opt in TensorRT input shape) even if it works for other input tensor shapes (min and max in param). 
My understanding is that in your case the engine building parameters are different from the benchmark setup (batch size 1 and 32). This may produce surprising results.

I would therefore advice you to build for a target similar to your benchmark setup. In my tests even small models gain some speed up with quantization but less than base flavor of the same model.

**Comment by DeDeckerThomas** [comment]
Oh okay, I didn't know that. Interesting 🤔 
Thank you for your answer! I will give it a try and see what the results are :)
