### ISSUE TITLE
Error in docker container using pip install

### ISSUE THREAD

**Issue by lakshaykc** [ELS-RD/transformer-deploy#88]
**What is happening?**
I'm using the docker container `ghcr.io/els-rd/transformer-deploy:0.4.0` to run the embeddings example in the doc using the following command:

```
convert_model -m sentence-transformers/msmarco-distilbert-cos-v5 --backend onnx --task embedding --seq-len 128 128 128
```

When I launch the container and run the above command, I get the expected output without any issues. However, if I update the `transformer-deploy` package using `pip install .` and then run the above command, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/convert_model", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 388, in entrypoint
    main(commands=args)
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 355, in main
    ort_output, time_buffer = launch_inference(
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 113, in launch_inference
    output = infer(batch_input)
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/convert.py", line 351, in infer_ort
    results = inference_onnx_binding(model_onnx=ort_model, inputs=inputs, device=commands.device)
  File "/usr/local/lib/python3.8/dist-packages/transformer_deploy/backends/ort_utils.py", line 255, in inference_onnx_binding
    binding.synchronize_inputs()
AttributeError: 'IOBinding' object has no attribute 'synchronize_inputs'
```

I want to try something which requires changing some lines in the `convert.py` file. I was hoping to install using pip after making the change and running test command as illustrated above. Is there more to installing the package? Or is this a bug?

**To Reproduce**
```
git clone git@github.com:ELS-RD/transformer-deploy.git
cd transformer-deploy
# docker image may take a few minutes
docker pull ghcr.io/els-rd/transformer-deploy:0.4.0 

# run the docker container
docker run -it --rm --gpus all  -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 bash

# run the following commands from inside the container
# run test command. This should run without any issues
convert_model -m sentence-transformers/msmarco-distilbert-cos-v5 --backend onnx --task embedding --seq-len 128 128 128

# install transformer-deploy from the latest commit
pip install .

# run the test command again and it will error out
convert_model -m sentence-transformers/msmarco-distilbert-cos-v5 --backend onnx --task embedding --seq-len 128 128 128

```

**Summary**
After installing the latest commit in the docker container, `convert` command errors out. Is there a different installation procedure ? Or is this a bug?

**Comment by pommedeterresautee** [comment]
`synchronize_inputs` is only present on the last version of Onnx Runtime. The `master` branch is based on last ORT version.
The docker version you are using is based on an old version of ORT.
I think that if you just update ORT in Docker (through bash or whatever) during runtime it should fix this issue.
